### ISSUE TITLE
Add placeholder crate for `lpc845`

### ISSUE THREAD

**Issue by hannobraun** [lpc-rs/lpc-placeholders#2]
cc @david-sawatzke

**Comment by david-sawatzke** [comment]
I don't think we need it, as no crate with that name currently exists & i don't see a reason why someone would create it. This situation is better than having a "please look somewhere else" crate as the top result.

**Comment by hannobraun** [comment]
That makes a lot of sense, actually. I guess I'm concerned about someone else coming in and snatching the name (maliciously or accidentally), but that's probably not a good enough reason to reserve it.
